version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    ports:
      - "25565:25565"
    environment:
      # BASE CONFIGURATION
      EULA: "TRUE"
      MEMORY: "5G"
      TYPE: "FORGE"
      VERSION: "1.20.1" 
      ONLINE_MODE: "FALSE"
      MOTD: "Antorlok´s Minecraft Server"
      # AUTOMATIC MODS DOWNLOAD
      MODRINTH_PROJECTS: "simply-swords, architectury-api, appleskin, waystones, cloth-config, balm"
      
      # TEXTURE PACK (RESOURCE PACK)
      RESOURCE_PACK: "https://github.com/Faithful-Resource-Pack/Faithful-Java-32x/releases/download/1.20/Faithful_32x_1.20.1.zip"
      REQUIRE_RESOURCE_PACK: "false"

    volumes:
      - ./data:/data
      - ./server.properties:/data/server.properties
    restart: unless-stopped