# --- PERFORMANCE AND OPTIMIZATION ---
view-distance=10
simulation-distance=10
max-tick-time=60000
allow-flight=false
max-world-size=29999984
network-compression-threshold=256

# --- GAMEPLAY ---
gamemode=survival
force-gamemode=false
difficulty=normal
pvp=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
generate-structures=true
allow-nether=true

# --- SECURITY AND CONNECTION ---
max-players=20
enforce-secure-profile=false

# --- TEXTURES ---
resource-pack=
require-resource-pack=false